"""Added google user id to user model

Revision ID: 31d8aacd18e8
Revises: 9eea6daf32fe
Create Date: 2026-01-21 20:38:05.779020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31d8aacd18e8'
down_revision: Union[str, None] = '9eea6daf32fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_milestone_date', table_name='milestone')
    op.drop_index('idx_milestone_project_id', table_name='milestone')
    op.drop_index('idx_milestone_status', table_name='milestone')
    op.drop_table('milestone')
    op.drop_column('project_member', 'role')
    op.add_column('user', sa.Column('google_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_user_id')
    op.add_column('project_member', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'member'::character varying"), autoincrement=False, nullable=True))
    op.create_table('milestone',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='milestone_created_by_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='milestone_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='milestone_pkey')
    )
    op.create_index('idx_milestone_status', 'milestone', ['status'], unique=False)
    op.create_index('idx_milestone_project_id', 'milestone', ['project_id'], unique=False)
    op.create_index('idx_milestone_date', 'milestone', ['date'], unique=False)
    # ### end Alembic commands ###
